services:
  react-ssr:
    build:
      context: .
      args:
        - BUILD_VERSION=1.0.0
    ports:
      - 8080:8080
    environment:
      - APP_ENV=prod
    restart: unless-stopped
    command: --bind 0.0.0.0:8080
